C = { 'TTT': { 'aa': 'Phe', 'freq': 0.46 }, 'TTC': { 'aa': 'Phe', 'freq': 0.54 }, 'TTA': { 'aa': 'Leu', 'freq': 0.08 },
      'TTG': { 'aa': 'Leu', 'freq': 0.13 }, 'CTT': { 'aa': 'Leu', 'freq': 0.13 }, 'CTC': { 'aa': 'Leu', 'freq': 0.2 },
      'CTA': { 'aa': 'Leu', 'freq': 0.07 }, 'CTG': { 'aa': 'Leu', 'freq': 0.4 }, 'ATT': { 'aa': 'Ile', 'freq': 0.36 },
      'ATC': { 'aa': 'Ile', 'freq': 0.47 }, 'ATA': { 'aa': 'Ile', 'freq': 0.17 }, 'ATG': { 'aa': 'Met', 'freq': 1.0 },
      'GTT': { 'aa': 'Val', 'freq': 0.18 }, 'GTC': { 'aa': 'Val', 'freq': 0.24 }, 'GTA': { 'aa': 'Val', 'freq': 0.12 },
      'GTG': { 'aa': 'Val', 'freq': 0.46 }, 'TCT': { 'aa': 'Ser', 'freq': 0.19 }, 'TCC': { 'aa': 'Ser', 'freq': 0.22 },
      'TCA': { 'aa': 'Ser', 'freq': 0.15 }, 'TCG': { 'aa': 'Ser', 'freq': 0.05 }, 'CCT': { 'aa': 'Pro', 'freq': 0.29 },
      'CCC': { 'aa': 'Pro', 'freq': 0.32 }, 'CCA': { 'aa': 'Pro', 'freq': 0.28 }, 'CCG': { 'aa': 'Pro', 'freq': 0.11 },
      'ACT': { 'aa': 'Thr', 'freq': 0.25 }, 'ACC': { 'aa': 'Thr', 'freq': 0.36 }, 'ACA': { 'aa': 'Thr', 'freq': 0.28 },
      'ACG': { 'aa': 'Thr', 'freq': 0.11 }, 'GCT': { 'aa': 'Ala', 'freq': 0.27 }, 'GCC': { 'aa': 'Ala', 'freq': 0.4 },
      'GCA': { 'aa': 'Ala', 'freq': 0.23 }, 'GCG': { 'aa': 'Ala', 'freq': 0.11 }, 'TAT': { 'aa': 'Tyr', 'freq': 0.44 },
      'TAC': { 'aa': 'Tyr', 'freq': 0.56 }, 'TAA': { 'aa': 'Ter', 'freq': 0.3 }, 'TAG': { 'aa': 'Ter', 'freq': 0.24 },
      'CAT': { 'aa': 'His', 'freq': 0.42 }, 'CAC': { 'aa': 'His', 'freq': 0.58 }, 'CAA': { 'aa': 'Gln', 'freq': 0.27 },
      'CAG': { 'aa': 'Gln', 'freq': 0.73 }, 'AAT': { 'aa': 'Asn', 'freq': 0.47 }, 'AAC': { 'aa': 'Asn', 'freq': 0.53 },
      'AAA': { 'aa': 'Lys', 'freq': 0.43 }, 'AAG': { 'aa': 'Lys', 'freq': 0.57 }, 'GAT': { 'aa': 'Asp', 'freq': 0.46 },
      'GAC': { 'aa': 'Asp', 'freq': 0.54 }, 'GAA': { 'aa': 'Glu', 'freq': 0.42 }, 'GAG': { 'aa': 'Glu', 'freq': 0.58 },
      'TGT': { 'aa': 'Cys', 'freq': 0.46 }, 'TGC': { 'aa': 'Cys', 'freq': 0.54 }, 'TGA': { 'aa': 'Ter', 'freq': 0.47 },
      'TGG': { 'aa': 'Trp', 'freq': 1.0 }, 'CGT': { 'aa': 'Arg', 'freq': 0.08 }, 'CGC': { 'aa': 'Arg', 'freq': 0.18 },
      'CGA': { 'aa': 'Arg', 'freq': 0.11 }, 'CGG': { 'aa': 'Arg', 'freq': 0.2 }, 'AGT': { 'aa': 'Ser', 'freq': 0.15 },
      'AGC': { 'aa': 'Ser', 'freq': 0.24 }, 'AGA': { 'aa': 'Arg', 'freq': 0.21 }, 'AGG': { 'aa': 'Arg', 'freq': 0.21 },
      'GGT': { 'aa': 'Gly', 'freq': 0.16 }, 'GGC': { 'aa': 'Gly', 'freq': 0.34 }, 'GGA': { 'aa': 'Gly', 'freq': 0.25 },
      'GGG': { 'aa': 'Gly', 'freq': 0.25 } }
