# DNA sequence
# S = "ATGTACATACAGTAA"     # Y, I, Q
# S = "TATAATGTACATACAGTAA"     # Y, I, Q
# S = "TACATACAGTAA"     # Y, I, Q
# S = "ATGTACATACAG"     # Y, I, Q
# S = "TACATACAGATG"     # Y, I, Q
# S = "TACATACAGATACAGATG"     # Y, I, Q
# S = "ATG"     # Y, I, Q
# S = ''     # Y, I, Q
S = "TTACATACAGATGTACATACAGTAATACATACAGTAATACATACAGATGTACATACAGTAA"
