name: BioSynth via Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # Every day at 00:00 UTC

jobs:
  test-gui-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: pip install poetry

      - name: pyqt5 handling
        run: |
          poetry remove pyqt5-qt5
          poetry add pyqt5==5.15.9 pyqt5-sip==12.11.0
          poetry lock --no-cache --regenerate

      - name: Install dependencies
        run: poetry install

      - name: Run BioSynth
        run: poetry run biosynth -g
        timeout-minutes: 1
